<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ1fhedc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ1fhedc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ1fhedc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ1fhedc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ1fhedc\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z1fhedc',
    'container.build_id' => '09798c22',
    'container.build_time' => 1661951604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ1fhedc');
