<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP85wBMl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP85wBMl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP85wBMl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP85wBMl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP85wBMl\App_KernelDevDebugContainer([
    'container.build_hash' => 'P85wBMl',
    'container.build_id' => '1013cfd0',
    'container.build_time' => 1661950131,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP85wBMl');
